language: ruby
rvm: 
  - 2.4.2
script: bundle exec rspec spec
services:
  - postgresql
  - redis
before_script:
  - psql -c 'create database remail_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test